# Generated by Django 5.0.6 on 2024-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(max_length=200)),
                ('global_x', models.FloatField()),
                ('global_y', models.FloatField()),
                ('global_z', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('fov', models.PositiveIntegerField()),
                ('gene', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
